name: cvs_completer
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.0+1
  riverpod: ^2.5.1
  hooks_riverpod:
  flutter_riverpod: ^2.5.1
  collection: ^1.16.0 
  dartz:
  dio:
  talker_dio_logger:
  intl: ^0.18.0
  csv: ^6.0.0
  image_picker_web: ^3.1.1
  grpc: ^3.0.2
  flutter_hooks: ^0.20.5
  amazon_cognito_identity_dart_2: ^3.0.3
  freezed_annotation: ^2.4.1
  fixnum: ^1.0.1
  jwt_decode: ^0.3.1
  enchanted_collection: ^1.3.0
  file_saver: ^0.2.12
  dsf_ms_proto:
    git:
      url: git@github.com:dreamstock/dsf-ms-proto.git
      ref: 3.58.0
      path: dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  flutter_lints: ^3.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
